//
//  MockJSONData.swift
//  New-GitHub
//
//  Created by David Mansourian on 2024-02-09.
//

import Foundation

// 9 user search results
let mockSearch_userResultsData = """
{
  "total_count": 9,
  "incomplete_results": false,
  "items": [
    {
      "login": "apple",
      "id": 10639145,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjEwNjM5MTQ1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10639145?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/apple",
      "html_url": "https://github.com/apple",
      "followers_url": "https://api.github.com/users/apple/followers",
      "following_url": "https://api.github.com/users/apple/following{/other_user}",
      "gists_url": "https://api.github.com/users/apple/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/apple/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/apple/subscriptions",
      "organizations_url": "https://api.github.com/users/apple/orgs",
      "repos_url": "https://api.github.com/users/apple/repos",
      "events_url": "https://api.github.com/users/apple/events{/privacy}",
      "received_events_url": "https://api.github.com/users/apple/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "appleboy",
      "id": 21979,
      "node_id": "MDQ6VXNlcjIxOTc5",
      "avatar_url": "https://avatars.githubusercontent.com/u/21979?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/appleboy",
      "html_url": "https://github.com/appleboy",
      "followers_url": "https://api.github.com/users/appleboy/followers",
      "following_url": "https://api.github.com/users/appleboy/following{/other_user}",
      "gists_url": "https://api.github.com/users/appleboy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/appleboy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/appleboy/subscriptions",
      "organizations_url": "https://api.github.com/users/appleboy/orgs",
      "repos_url": "https://api.github.com/users/appleboy/repos",
      "events_url": "https://api.github.com/users/appleboy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/appleboy/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "apple-oss-distributions",
      "id": 91919287,
      "node_id": "O_kgDOBXqTtw",
      "avatar_url": "https://avatars.githubusercontent.com/u/91919287?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/apple-oss-distributions",
      "html_url": "https://github.com/apple-oss-distributions",
      "followers_url": "https://api.github.com/users/apple-oss-distributions/followers",
      "following_url": "https://api.github.com/users/apple-oss-distributions/following{/other_user}",
      "gists_url": "https://api.github.com/users/apple-oss-distributions/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/apple-oss-distributions/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/apple-oss-distributions/subscriptions",
      "organizations_url": "https://api.github.com/users/apple-oss-distributions/orgs",
      "repos_url": "https://api.github.com/users/apple-oss-distributions/repos",
      "events_url": "https://api.github.com/users/apple-oss-distributions/events{/privacy}",
      "received_events_url": "https://api.github.com/users/apple-oss-distributions/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "appleton",
      "id": 241576,
      "node_id": "MDQ6VXNlcjI0MTU3Ng==",
      "avatar_url": "https://avatars.githubusercontent.com/u/241576?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/appleton",
      "html_url": "https://github.com/appleton",
      "followers_url": "https://api.github.com/users/appleton/followers",
      "following_url": "https://api.github.com/users/appleton/following{/other_user}",
      "gists_url": "https://api.github.com/users/appleton/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/appleton/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/appleton/subscriptions",
      "organizations_url": "https://api.github.com/users/appleton/orgs",
      "repos_url": "https://api.github.com/users/appleton/repos",
      "events_url": "https://api.github.com/users/appleton/events{/privacy}",
      "received_events_url": "https://api.github.com/users/appleton/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "opensource-apple",
      "id": 2146303,
      "node_id": "MDQ6VXNlcjIxNDYzMDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2146303?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/opensource-apple",
      "html_url": "https://github.com/opensource-apple",
      "followers_url": "https://api.github.com/users/opensource-apple/followers",
      "following_url": "https://api.github.com/users/opensource-apple/following{/other_user}",
      "gists_url": "https://api.github.com/users/opensource-apple/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/opensource-apple/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/opensource-apple/subscriptions",
      "organizations_url": "https://api.github.com/users/opensource-apple/orgs",
      "repos_url": "https://api.github.com/users/opensource-apple/repos",
      "events_url": "https://api.github.com/users/opensource-apple/events{/privacy}",
      "received_events_url": "https://api.github.com/users/opensource-apple/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "apple-opensource",
      "id": 23200344,
      "node_id": "MDQ6VXNlcjIzMjAwMzQ0",
      "avatar_url": "https://avatars.githubusercontent.com/u/23200344?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/apple-opensource",
      "html_url": "https://github.com/apple-opensource",
      "followers_url": "https://api.github.com/users/apple-opensource/followers",
      "following_url": "https://api.github.com/users/apple-opensource/following{/other_user}",
      "gists_url": "https://api.github.com/users/apple-opensource/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/apple-opensource/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/apple-opensource/subscriptions",
      "organizations_url": "https://api.github.com/users/apple-opensource/orgs",
      "repos_url": "https://api.github.com/users/apple-opensource/repos",
      "events_url": "https://api.github.com/users/apple-opensource/events{/privacy}",
      "received_events_url": "https://api.github.com/users/apple-opensource/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "appledesire",
      "id": 103173953,
      "node_id": "U_kgDOBiZPQQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/103173953?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/appledesire",
      "html_url": "https://github.com/appledesire",
      "followers_url": "https://api.github.com/users/appledesire/followers",
      "following_url": "https://api.github.com/users/appledesire/following{/other_user}",
      "gists_url": "https://api.github.com/users/appledesire/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/appledesire/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/appledesire/subscriptions",
      "organizations_url": "https://api.github.com/users/appledesire/orgs",
      "repos_url": "https://api.github.com/users/appledesire/repos",
      "events_url": "https://api.github.com/users/appledesire/events{/privacy}",
      "received_events_url": "https://api.github.com/users/appledesire/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "guopingxiao",
      "id": 11886494,
      "node_id": "MDQ6VXNlcjExODg2NDk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/11886494?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guopingxiao",
      "html_url": "https://github.com/guopingxiao",
      "followers_url": "https://api.github.com/users/guopingxiao/followers",
      "following_url": "https://api.github.com/users/guopingxiao/following{/other_user}",
      "gists_url": "https://api.github.com/users/guopingxiao/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guopingxiao/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guopingxiao/subscriptions",
      "organizations_url": "https://api.github.com/users/guopingxiao/orgs",
      "repos_url": "https://api.github.com/users/guopingxiao/repos",
      "events_url": "https://api.github.com/users/guopingxiao/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guopingxiao/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "LappleApple",
      "id": 2453640,
      "node_id": "MDQ6VXNlcjI0NTM2NDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2453640?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LappleApple",
      "html_url": "https://github.com/LappleApple",
      "followers_url": "https://api.github.com/users/LappleApple/followers",
      "following_url": "https://api.github.com/users/LappleApple/following{/other_user}",
      "gists_url": "https://api.github.com/users/LappleApple/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LappleApple/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LappleApple/subscriptions",
      "organizations_url": "https://api.github.com/users/LappleApple/orgs",
      "repos_url": "https://api.github.com/users/LappleApple/repos",
      "events_url": "https://api.github.com/users/LappleApple/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LappleApple/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""".data(using: .utf8)!

let mockSearch_invalidData = """
{
  "total_coun": 9,
  "incomplete_results": false,
  "iems": [
    {
      "lgin": "apple",
      "i": 10639145,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjEwNjM5MTQ1",
      "avatar_url": "https://avatars.githubusercontent.com/u/10639145?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/apple",
      "html_url": "https://github.com/apple",
      "followers_url": "https://api.github.com/users/apple/followers",
      "following_url": "https://api.github.com/users/apple/following{/other_user}",
      "gists_url": "https://api.github.com/users/apple/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/apple/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/apple/subscriptions",
      "organizations_url": "https://api.github.com/users/apple/orgs",
      "repos_url": "https://api.github.com/users/apple/repos",
      "events_url": "https://api.github.com/users/apple/events{/privacy}",
      "received_events_url": "https://api.github.com/users/apple/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""".data(using: .utf8)!

let mockProfile_userInfo_apple = """
{
  "login": "apple",
  "id": 10639145,
  "node_id": "MDEyOk9yZ2FuaXphdGlvbjEwNjM5MTQ1",
  "avatar_url": "https://avatars.githubusercontent.com/u/10639145?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/apple",
  "html_url": "https://github.com/apple",
  "followers_url": "https://api.github.com/users/apple/followers",
  "following_url": "https://api.github.com/users/apple/following{/other_user}",
  "gists_url": "https://api.github.com/users/apple/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/apple/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/apple/subscriptions",
  "organizations_url": "https://api.github.com/users/apple/orgs",
  "repos_url": "https://api.github.com/users/apple/repos",
  "events_url": "https://api.github.com/users/apple/events{/privacy}",
  "received_events_url": "https://api.github.com/users/apple/received_events",
  "type": "Organization",
  "site_admin": false,
  "name": "Apple",
  "company": null,
  "blog": "https://apple.com",
  "location": "Cupertino, CA",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 285,
  "public_gists": 0,
  "followers": 20780,
  "following": 0,
  "created_at": "2015-01-21T20:19:28Z",
  "updated_at": "2023-05-17T22:06:06Z"
}
""".data(using: .utf8)!
